FROM pygatb/alpine_runtime_base

RUN apk --no-cache add cmake make g++ zlib-dev python3-dev  git
RUN pip3 install --no-cache-dir Cython --install-option="--no-cython-compile"

CMD ["py-gatb-compile.sh"]
COPY py-gatb-compile.sh /usr/local/bin/
